apiVersion: v1
kind: Service
metadata:
  name: http-svc
spec:
  selector:
    app: asyoulike-web
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
